import { Country } from './types';


// Manually defined canonical dataset keyed by iso2. This is the authoritative source.
export const countriesByIso2: Record<string, Country> = {
  af: { name: 'Afghanistan', regions: ['asia'], iso2: 'af', dialCode: '93' },
  al: { name: 'Albania', regions: ['europe'], iso2: 'al', dialCode: '355' },
  dz: { name: 'Algeria', regions: ['africa', 'north-africa'], iso2: 'dz', dialCode: '213' },
  as: { name: 'American Samoa', regions: ['oceania'], iso2: 'as', dialCode: '1684' },
  ad: { name: 'Andorra', regions: ['europe'], iso2: 'ad', dialCode: '376' },
  ao: { name: 'Angola', regions: ['africa'], iso2: 'ao', dialCode: '244' },
  ai: { name: 'Anguilla', regions: ['america', 'carribean'], iso2: 'ai', dialCode: '1264' },
  ag: { name: 'Antigua and Barbuda', regions: ['america', 'carribean'], iso2: 'ag', dialCode: '1268' },
  ar: { name: 'Argentina', regions: ['america', 'south-america'], iso2: 'ar', dialCode: '54', format: '+.. (..) ........' },
  am: { name: 'Armenia', regions: ['asia', 'ex-ussr'], iso2: 'am', dialCode: '374' },
  aw: { name: 'Aruba', regions: ['america', 'carribean'], iso2: 'aw', dialCode: '297' },
  au: { name: 'Australia', regions: ['oceania'], iso2: 'au', dialCode: '61', format: '+.. ... ... ...' },
  at: { name: 'Austria', regions: ['europe', 'european-union'], iso2: 'at', dialCode: '43' },
  az: { name: 'Azerbaijan', regions: ['asia', 'ex-ussr'], iso2: 'az', dialCode: '994' },
  bs: { name: 'Bahamas', regions: ['america', 'carribean'], iso2: 'bs', dialCode: '1242' },
  bh: { name: 'Bahrain', regions: ['middle-east'], iso2: 'bh', dialCode: '973' },
  bd: { name: 'Bangladesh', regions: ['asia'], iso2: 'bd', dialCode: '880' },
  bb: { name: 'Barbados', regions: ['america', 'carribean'], iso2: 'bb', dialCode: '1246' },
  by: { name: 'Belarus', regions: ['europe', 'ex-ussr'], iso2: 'by', dialCode: '375', format: '+... (..) ... .. ..' },
  be: { name: 'Belgium', regions: ['europe', 'european-union'], iso2: 'be', dialCode: '32', format: '+.. ... .. .. ..' },
  bz: { name: 'Belize', regions: ['america', 'central-america'], iso2: 'bz', dialCode: '501' },
  bj: { name: 'Benin', regions: ['africa'], iso2: 'bj', dialCode: '229', format: '+... .... ....' },
  bm: { name: 'Bermuda', regions: ['america', 'north-america'], iso2: 'bm', dialCode: '1441' },
  bt: { name: 'Bhutan', regions: ['asia'], iso2: 'bt', dialCode: '975' },
  bo: { name: 'Bolivia', regions: ['america', 'south-america'], iso2: 'bo', dialCode: '591' },
  ba: { name: 'Bosnia and Herzegovina', regions: ['europe'], iso2: 'ba', dialCode: '387' },
  bw: { name: 'Botswana', regions: ['africa'], iso2: 'bw', dialCode: '267' },
  br: { name: 'Brazil', regions: ['america', 'south-america'], iso2: 'br', dialCode: '55', format: '+.. (..) .........' },
  io: { name: 'British Indian Ocean Territory', regions: ['asia'], iso2: 'io', dialCode: '246' },
  vg: { name: 'British Virgin Islands', regions: ['america', 'carribean'], iso2: 'vg', dialCode: '1284' },
  bn: { name: 'Brunei', regions: ['asia'], iso2: 'bn', dialCode: '673' },
  bg: { name: 'Bulgaria', regions: ['europe', 'european-union'], iso2: 'bg', dialCode: '359' },
  bf: { name: 'Burkina Faso', regions: ['africa'], iso2: 'bf', dialCode: '226', format: '+... .. .. .. ..' },
  bi: { name: 'Burundi', regions: ['africa'], iso2: 'bi', dialCode: '257', format: '+... .. .. .. ..' },
  kh: { name: 'Cambodia', regions: ['asia'], iso2: 'kh', dialCode: '855' },
  cm: { name: 'Cameroon', regions: ['africa'], iso2: 'cm', dialCode: '237' },
  ca: { name: 'Canada', regions: ['america', 'north-america'], iso2: 'ca', dialCode: '1', format: '+. (...) ...-....', priority: 1, areaCodes: ['204', '236', '249', '250', '289', '306', '343', '365', '387', '403', '416', '418', '431', '437', '438', '450', '506', '514', '519', '548', '579', '581', '587', '604', '613', '639', '647', '672', '705', '709', '742', '778', '780', '782', '807', '819', '825', '867', '873', '902', '905'] },
  cv: { name: 'Cape Verde', regions: ['africa'], iso2: 'cv', dialCode: '238', format: '+... ... .. ..' },
  bq: { name: 'Caribbean Netherlands', regions: ['america', 'carribean'], iso2: 'bq', dialCode: '599', priority: 1 },
  ky: { name: 'Cayman Islands', regions: ['america', 'carribean'], iso2: 'ky', dialCode: '1345' },
  cf: { name: 'Central African Republic', regions: ['africa'], iso2: 'cf', dialCode: '236', format: '+... .... ....' },
  td: { name: 'Chad', regions: ['africa'], iso2: 'td', dialCode: '235', format: '+... .. .. .. ..' },
  cl: { name: 'Chile', regions: ['america', 'south-america'], iso2: 'cl', dialCode: '56' },
  cn: { name: 'China', regions: ['asia'], iso2: 'cn', dialCode: '86', format: '+.. ..-.........' },
  co: { name: 'Colombia', regions: ['america', 'south-america'], iso2: 'co', dialCode: '57' },
  km: { name: 'Comoros', regions: ['africa'], iso2: 'km', dialCode: '269', format: '+... ... ....' },
  cd: { name: 'Congo', regions: ['africa'], iso2: 'cd', dialCode: '243' },
  cg: { name: 'Congo', regions: ['africa'], iso2: 'cg', dialCode: '242', format: '+... .. .. .....' },
  ck: { name: 'Cook Islands', regions: ['oceania'], iso2: 'ck', dialCode: '682' },
  cr: { name: 'Costa Rica', regions: ['america', 'central-america'], iso2: 'cr', dialCode: '506', format: '+... ....-....' },
  ci: { name: 'Côte d’Ivoire', regions: ['africa'], iso2: 'ci', dialCode: '225', format: '+... .. .. .. ..' },
  hr: { name: 'Croatia', regions: ['europe', 'european-union'], iso2: 'hr', dialCode: '385' },
  cu: { name: 'Cuba', regions: ['america', 'carribean'], iso2: 'cu', dialCode: '53' },
  cw: { name: 'Curaçao', regions: ['america', 'carribean'], iso2: 'cw', dialCode: '599', priority: 0 },
  cy: { name: 'Cyprus', regions: ['europe', 'european-union'], iso2: 'cy', dialCode: '357', format: '+... .. ......' },
  cz: { name: 'Czech Republic', regions: ['europe', 'european-union'], iso2: 'cz', dialCode: '420' },
  dk: { name: 'Denmark', regions: ['europe', 'european-union'], iso2: 'dk', dialCode: '45', format: '+.. .. .. .. ..' },
  dj: { name: 'Djibouti', regions: ['africa'], iso2: 'dj', dialCode: '253' },
  dm: { name: 'Dominica', regions: ['america', 'carribean'], iso2: 'dm', dialCode: '1767' },
  do: { name: 'Dominican Republic', regions: ['america', 'carribean'], iso2: 'do', dialCode: '1', priority: 2, areaCodes: ['809', '829', '849'] },
  ec: { name: 'Ecuador', regions: ['america', 'south-america'], iso2: 'ec', dialCode: '593' },
  eg: { name: 'Egypt', regions: ['africa', 'north-africa'], iso2: 'eg', dialCode: '20' },
  sv: { name: 'El Salvador', regions: ['america', 'central-america'], iso2: 'sv', dialCode: '503', format: '+... ....-....' },
  gq: { name: 'Equatorial Guinea', regions: ['africa'], iso2: 'gq', dialCode: '240', format: '+... .. ... ....' },
  er: { name: 'Eritrea', regions: ['africa'], iso2: 'er', dialCode: '291' },
  ee: { name: 'Estonia', regions: ['europe', 'european-union', 'ex-ussr'], iso2: 'ee', dialCode: '372', format: '+... .... ......' },
  et: { name: 'Ethiopia', regions: ['africa'], iso2: 'et', dialCode: '251' },
  fk: { name: 'Falkland Islands', regions: ['america', 'south-america'], iso2: 'fk', dialCode: '500' },
  fo: { name: 'Faroe Islands', regions: ['europe'], iso2: 'fo', dialCode: '298' },
  fj: { name: 'Fiji', regions: ['oceania'], iso2: 'fj', dialCode: '679' },
  fi: { name: 'Finland', regions: ['europe', 'european-union'], iso2: 'fi', dialCode: '358', format: '+... .. ... .. ..' },
  fr: { name: 'France', regions: ['europe', 'european-union'], iso2: 'fr', dialCode: '33', format: '+.. . .. .. .. ..' },
  gf: { name: 'French Guiana', regions: ['america', 'south-america'], iso2: 'gf', dialCode: '594' },
  pf: { name: 'French Polynesia', regions: ['oceania'], iso2: 'pf', dialCode: '689' },
  ga: { name: 'Gabon', regions: ['africa'], iso2: 'ga', dialCode: '241', format: '+... .. .. .. ..' },
  gm: { name: 'Gambia', regions: ['africa'], iso2: 'gm', dialCode: '220' },
  ge: { name: 'Georgia', regions: ['asia', 'ex-ussr'], iso2: 'ge', dialCode: '995' },
  de: { name: 'Germany', regions: ['europe', 'european-union'], iso2: 'de', dialCode: '49', format: '+.. .... ........' },
  gh: { name: 'Ghana', regions: ['africa'], iso2: 'gh', dialCode: '233' },
  gi: { name: 'Gibraltar', regions: ['europe'], iso2: 'gi', dialCode: '350' },
  gr: { name: 'Greece', regions: ['europe', 'european-union'], iso2: 'gr', dialCode: '30' },
  gl: { name: 'Greenland', regions: ['america'], iso2: 'gl', dialCode: '299' },
  gd: { name: 'Grenada', regions: ['america', 'carribean'], iso2: 'gd', dialCode: '1473' },
  gp: { name: 'Guadeloupe', regions: ['america', 'carribean'], iso2: 'gp', dialCode: '590', priority: 0 },
  gu: { name: 'Guam', regions: ['oceania'], iso2: 'gu', dialCode: '1671' },
  gt: { name: 'Guatemala', regions: ['america', 'central-america'], iso2: 'gt', dialCode: '502', format: '+... ....-....' },
  gn: { name: 'Guinea', regions: ['africa'], iso2: 'gn', dialCode: '224', format: '+... . ... ....' },
  gw: { name: 'Guinea-Bissau', regions: ['africa'], iso2: 'gw', dialCode: '245' },
  gy: { name: 'Guyana', regions: ['america', 'south-america'], iso2: 'gy', dialCode: '592' },
  ht: { name: 'Haiti', regions: ['america', 'carribean'], iso2: 'ht', dialCode: '509', format: '+... ....-....' },
  hn: { name: 'Honduras', regions: ['america', 'central-america'], iso2: 'hn', dialCode: '504' },
  hk: { name: 'Hong Kong', regions: ['asia'], iso2: 'hk', dialCode: '852', format: '+... .... ....' },
  hu: { name: 'Hungary', regions: ['europe', 'european-union'], iso2: 'hu', dialCode: '36' },
  is: { name: 'Iceland', regions: ['europe'], iso2: 'is', dialCode: '354', format: '+... ... ....' },
  in: { name: 'India', regions: ['asia'], iso2: 'in', dialCode: '91', format: '+.. .....-.....' },
  id: { name: 'Indonesia', regions: ['asia'], iso2: 'id', dialCode: '62' },
  ir: { name: 'Iran', regions: ['middle-east'], iso2: 'ir', dialCode: '98' },
  iq: { name: 'Iraq', regions: ['middle-east'], iso2: 'iq', dialCode: '964' },
  ie: { name: 'Ireland', regions: ['europe', 'european-union'], iso2: 'ie', dialCode: '353', format: '+... .. .......' },
  il: { name: 'Israel', regions: ['middle-east'], iso2: 'il', dialCode: '972', format: '+... ... ... ....' },
  it: { name: 'Italy', regions: ['europe', 'european-union'], iso2: 'it', dialCode: '39', format: '+.. ... .......', priority: 0 },
  jm: { name: 'Jamaica', regions: ['america', 'carribean'], iso2: 'jm', dialCode: '1876' },
  jp: { name: 'Japan', regions: ['asia'], iso2: 'jp', dialCode: '81', format: '+.. .. .... ....' },
  jo: { name: 'Jordan', regions: ['middle-east'], iso2: 'jo', dialCode: '962' },
  kz: { name: 'Kazakhstan', regions: ['asia', 'ex-ussr'], iso2: 'kz', dialCode: '7', format: '+. ... ...-..-..', priority: 1, areaCodes: ['313', '327', '7172', '312', '73622', '321', '324', '336', '318', '315', '325', '311', '326', '310'] },
  ke: { name: 'Kenya', regions: ['africa'], iso2: 'ke', dialCode: '254' },
  ki: { name: 'Kiribati', regions: ['oceania'], iso2: 'ki', dialCode: '686' },
  ks: { name: 'Kosovo', regions: ['europe'], iso2: 'ks', dialCode: '383' },
  kw: { name: 'Kuwait', regions: ['middle-east'], iso2: 'kw', dialCode: '965' },
  kg: { name: 'Kyrgyzstan', regions: ['asia', 'ex-ussr'], iso2: 'kg', dialCode: '996' },
  la: { name: 'Laos', regions: ['asia'], iso2: 'la', dialCode: '856' },
  lv: { name: 'Latvia', regions: ['europe', 'european-union', 'ex-ussr'], iso2: 'lv', dialCode: '371' },
  lb: { name: 'Lebanon', regions: ['middle-east'], iso2: 'lb', dialCode: '961' },
  ls: { name: 'Lesotho', regions: ['africa'], iso2: 'ls', dialCode: '266' },
  lr: { name: 'Liberia', regions: ['africa'], iso2: 'lr', dialCode: '231' },
  ly: { name: 'Libya', regions: ['africa', 'north-africa'], iso2: 'ly', dialCode: '218' },
  li: { name: 'Liechtenstein', regions: ['europe'], iso2: 'li', dialCode: '423' },
  lt: { name: 'Lithuania', regions: ['europe', 'european-union', 'ex-ussr'], iso2: 'lt', dialCode: '370' },
  lu: { name: 'Luxembourg', regions: ['europe', 'european-union'], iso2: 'lu', dialCode: '352', format: '+.. . ... ... ...' },
  mo: { name: 'Macau', regions: ['asia'], iso2: 'mo', dialCode: '853' },
  mk: { name: 'Macedonia', regions: ['europe'], iso2: 'mk', dialCode: '389' },
  mg: { name: 'Madagascar', regions: ['africa'], iso2: 'mg', dialCode: '261', format: '+... .. . ......' },
  mw: { name: 'Malawi', regions: ['africa'], iso2: 'mw', dialCode: '265' },
  my: { name: 'Malaysia', regions: ['asia'], iso2: 'my', dialCode: '60', format: '+.. ..-....-....' },
  mv: { name: 'Maldives', regions: ['asia'], iso2: 'mv', dialCode: '960' },
  ml: { name: 'Mali', regions: ['africa'], iso2: 'ml', dialCode: '223', format: '+... .... ....' },
  mt: { name: 'Malta', regions: ['europe', 'european-union'], iso2: 'mt', dialCode: '356' },
  mh: { name: 'Marshall Islands', regions: ['oceania'], iso2: 'mh', dialCode: '692' },
  mq: { name: 'Martinique', regions: ['america', 'carribean'], iso2: 'mq', dialCode: '596' },
  mr: { name: 'Mauritania', regions: ['africa'], iso2: 'mr', dialCode: '222', format: '+... .... ....' },
  mu: { name: 'Mauritius', regions: ['africa'], iso2: 'mu', dialCode: '230', format: '+... . ... ....' },
  mx: { name: 'Mexico', regions: ['america', 'central-america'], iso2: 'mx', dialCode: '52' },
  fm: { name: 'Micronesia', regions: ['oceania'], iso2: 'fm', dialCode: '691' },
  md: { name: 'Moldova', regions: ['europe'], iso2: 'md', dialCode: '373', format: '+... (..) ..-..-..' },
  mc: { name: 'Monaco', regions: ['europe'], iso2: 'mc', dialCode: '377' },
  mn: { name: 'Mongolia', regions: ['asia'], iso2: 'mn', dialCode: '976' },
  me: { name: 'Montenegro', regions: ['europe'], iso2: 'me', dialCode: '382' },
  ms: { name: 'Montserrat', regions: ['america', 'carribean'], iso2: 'ms', dialCode: '1664' },
  ma: { name: 'Morocco', regions: ['africa', 'north-africa'], iso2: 'ma', dialCode: '212', format: '+212-.........' },
  mz: { name: 'Mozambique', regions: ['africa'], iso2: 'mz', dialCode: '258', format: '+... ... ......' },
  mm: { name: 'Myanmar', regions: ['asia'], iso2: 'mm', dialCode: '95' },
  na: { name: 'Namibia', regions: ['africa'], iso2: 'na', dialCode: '264' },
  nr: { name: 'Nauru', regions: ['africa'], iso2: 'nr', dialCode: '674' },
  np: { name: 'Nepal', regions: ['asia'], iso2: 'np', dialCode: '977' },
  nl: { name: 'Netherlands', regions: ['europe', 'european-union'], iso2: 'nl', dialCode: '31', format: '+.. .. ........' },
  nc: { name: 'New Caledonia', regions: ['oceania'], iso2: 'nc', dialCode: '687' },
  nz: { name: 'New Zealand', regions: ['oceania'], iso2: 'nz', dialCode: '64', format: '+.. ...-...-....' },
  ni: { name: 'Nicaragua', regions: ['america', 'central-america'], iso2: 'ni', dialCode: '505' },
  ne: { name: 'Niger', regions: ['africa'], iso2: 'ne', dialCode: '227', format: '+... .. .. .. ..' },
  ng: { name: 'Nigeria', regions: ['africa'], iso2: 'ng', dialCode: '234' },
  nu: { name: 'Niue', regions: ['asia'], iso2: 'nu', dialCode: '683' },
  nf: { name: 'Norfolk Island', regions: ['oceania'], iso2: 'nf', dialCode: '672' },
  kp: { name: 'North Korea', regions: ['asia'], iso2: 'kp', dialCode: '850' },
  mp: { name: 'Northern Mariana Islands', regions: ['oceania'], iso2: 'mp', dialCode: '1670' },
  no: { name: 'Norway', regions: ['europe'], iso2: 'no', dialCode: '47', format: '+.. ... .. ...' },
  om: { name: 'Oman', regions: ['middle-east'], iso2: 'om', dialCode: '968' },
  pk: { name: 'Pakistan', regions: ['asia'], iso2: 'pk', dialCode: '92', format: '+.. ...-.......' },
  pw: { name: 'Palau', regions: ['oceania'], iso2: 'pw', dialCode: '680' },
  ps: { name: 'Palestine', regions: ['middle-east'], iso2: 'ps', dialCode: '970' },
  pa: { name: 'Panama', regions: ['america', 'central-america'], iso2: 'pa', dialCode: '507' },
  pg: { name: 'Papua New Guinea', regions: ['oceania'], iso2: 'pg', dialCode: '675' },
  py: { name: 'Paraguay', regions: ['america', 'south-america'], iso2: 'py', dialCode: '595' },
  pe: { name: 'Peru', regions: ['america', 'south-america'], iso2: 'pe', dialCode: '51' },
  ph: { name: 'Philippines', regions: ['asia'], iso2: 'ph', dialCode: '63', format: '+.. .... .......' },
  pl: { name: 'Poland', regions: ['europe', 'european-union'], iso2: 'pl', dialCode: '48', format: '+.. ...-...-...' },
  pt: { name: 'Portugal', regions: ['europe', 'european-union'], iso2: 'pt', dialCode: '351' },
  pr: { name: 'Puerto Rico', regions: ['america', 'carribean'], iso2: 'pr', dialCode: '1', priority: 3, areaCodes: ['787', '939'] },
  qa: { name: 'Qatar', regions: ['middle-east'], iso2: 'qa', dialCode: '974' },
  re: { name: 'Réunion', regions: ['africa'], iso2: 're', dialCode: '262', format: '+.. . .. .. .. ..' },
  ro: { name: 'Romania', regions: ['europe', 'european-union'], iso2: 'ro', dialCode: '40' },
  ru: { name: 'Russia', regions: ['europe', 'asia', 'ex-ussr'], iso2: 'ru', dialCode: '7', format: '+. (...) ...-..-..', priority: 0 },
  rw: { name: 'Rwanda', regions: ['africa'], iso2: 'rw', dialCode: '250', format: '+... ... ... ...' },
  bl: { name: 'Saint Barthélemy', regions: ['america', 'carribean'], iso2: 'bl', dialCode: '590', priority: 1 },
  sh: { name: 'Saint Helena', regions: ['africa'], iso2: 'sh', dialCode: '290' },
  kn: { name: 'Saint Kitts and Nevis', regions: ['america', 'carribean'], iso2: 'kn', dialCode: '1869' },
  lc: { name: 'Saint Lucia', regions: ['america', 'carribean'], iso2: 'lc', dialCode: '1758' },
  mf: { name: 'Saint Martin', regions: ['america', 'carribean'], iso2: 'mf', dialCode: '590', priority: 2 },
  pm: { name: 'Saint Pierre and Miquelon', regions: ['america', 'north-america'], iso2: 'pm', dialCode: '508' },
  vc: { name: 'Saint Vincent and the Grenadines', regions: ['america', 'carribean'], iso2: 'vc', dialCode: '1784' },
  ws: { name: 'Samoa', regions: ['oceania'], iso2: 'ws', dialCode: '685' },
  sm: { name: 'San Marino', regions: ['europe'], iso2: 'sm', dialCode: '378' },
  st: { name: 'São Tomé and Príncipe', regions: ['africa'], iso2: 'st', dialCode: '239', format: '+... ... ....' },
  sa: { name: 'Saudi Arabia', regions: ['middle-east'], iso2: 'sa', dialCode: '966' },
  sn: { name: 'Senegal', regions: ['africa'], iso2: 'sn', dialCode: '221', format: '+... .. ... .. ..' },
  rs: { name: 'Serbia', regions: ['europe'], iso2: 'rs', dialCode: '381' },
  sc: { name: 'Seychelles', regions: ['africa'], iso2: 'sc', dialCode: '248', format: '+... ... ....' },
  sl: { name: 'Sierra Leone', regions: ['africa'], iso2: 'sl', dialCode: '232' },
  sg: { name: 'Singapore', regions: ['asia'], iso2: 'sg', dialCode: '65', format: '+.. ....-....' },
  sx: { name: 'Sint Maarten', regions: ['america', 'carribean'], iso2: 'sx', dialCode: '1721' },
  sk: { name: 'Slovakia', regions: ['europe', 'european-union'], iso2: 'sk', dialCode: '421' },
  si: { name: 'Slovenia', regions: ['europe', 'european-union'], iso2: 'si', dialCode: '386' },
  sb: { name: 'Solomon Islands', regions: ['oceania'], iso2: 'sb', dialCode: '677' },
  so: { name: 'Somalia', regions: ['africa'], iso2: 'so', dialCode: '252' },
  za: { name: 'South Africa', regions: ['africa'], iso2: 'za', dialCode: '27', format: '+.. .. ... ....' },
  kr: { name: 'South Korea', regions: ['asia'], iso2: 'kr', dialCode: '82', format: '+.. ... .... ....' },
  ss: { name: 'South Sudan', regions: ['africa', 'north-africa'], iso2: 'ss', dialCode: '211' },
  es: { name: 'Spain', regions: ['europe', 'european-union'], iso2: 'es', dialCode: '34', format: '+.. ... ... ...' },
  lk: { name: 'Sri Lanka', regions: ['asia'], iso2: 'lk', dialCode: '94' },
  sd: { name: 'Sudan', regions: ['africa'], iso2: 'sd', dialCode: '249' },
  sr: { name: 'Suriname', regions: ['america', 'south-america'], iso2: 'sr', dialCode: '597' },
  sz: { name: 'Swaziland', regions: ['africa'], iso2: 'sz', dialCode: '268' },
  se: { name: 'Sweden', regions: ['europe', 'european-union'], iso2: 'se', dialCode: '46', format: '+.. (..) ...-..-..' },
  ch: { name: 'Switzerland', regions: ['europe'], iso2: 'ch', dialCode: '41', format: '+.. .. ... .. ..' },
  sy: { name: 'Syria', regions: ['middle-east'], iso2: 'sy', dialCode: '963' },
  tw: { name: 'Taiwan', regions: ['asia'], iso2: 'tw', dialCode: '886' },
  tj: { name: 'Tajikistan', regions: ['asia', 'ex-ussr'], iso2: 'tj', dialCode: '992' },
  tz: { name: 'Tanzania', regions: ['africa'], iso2: 'tz', dialCode: '255' },
  th: { name: 'Thailand', regions: ['asia'], iso2: 'th', dialCode: '66' },
  tl: { name: 'Timor-Leste', regions: ['asia'], iso2: 'tl', dialCode: '670' },
  tg: { name: 'Togo', regions: ['africa'], iso2: 'tg', dialCode: '228', format: '+... ... .....' },
  tk: { name: 'Tokelau', regions: ['oceania'], iso2: 'tk', dialCode: '690' },
  to: { name: 'Tonga', regions: ['oceania'], iso2: 'to', dialCode: '676' },
  tt: { name: 'Trinidad and Tobago', regions: ['america', 'carribean'], iso2: 'tt', dialCode: '1868' },
  tn: { name: 'Tunisia', regions: ['africa', 'north-africa'], iso2: 'tn', dialCode: '216', format: '+... .. ... ...' },
  tr: { name: 'Turkey', regions: ['europe'], iso2: 'tr', dialCode: '90', format: '+.. ... ... .. ..' },
  tm: { name: 'Turkmenistan', regions: ['asia', 'ex-ussr'], iso2: 'tm', dialCode: '993' },
  tc: { name: 'Turks and Caicos Islands', regions: ['america', 'carribean'], iso2: 'tc', dialCode: '1649' },
  tv: { name: 'Tuvalu', regions: ['asia'], iso2: 'tv', dialCode: '688' },
  vi: { name: 'U.S. Virgin Islands', regions: ['america', 'carribean'], iso2: 'vi', dialCode: '1340' },
  ug: { name: 'Uganda', regions: ['africa'], iso2: 'ug', dialCode: '256' },
  ua: { name: 'Ukraine', regions: ['europe', 'ex-ussr'], iso2: 'ua', dialCode: '380', format: '+... (..) ... .. ..' },
  ae: { name: 'United Arab Emirates', regions: ['middle-east'], iso2: 'ae', dialCode: '971' },
  gb: { name: 'United Kingdom', regions: ['europe', 'european-union'], iso2: 'gb', dialCode: '44', format: '+.. .... ......' },
  us: { name: 'United States', regions: ['america', 'north-america'], iso2: 'us', dialCode: '1', format: '+. (...) ...-....', priority: 0, areaCodes: ['907', '205', '251', '256', '334', '479', '501', '870', '480', '520', '602', '623', '928', '209', '213', '310', '323', '408', '415', '510', '530', '559', '562', '619', '626', '650', '661', '707', '714', '760', '805', '818', '831', '858', '909', '916', '925', '949', '951', '303', '719', '970', '203', '860', '202', '302', '239', '305', '321', '352', '386', '407', '561', '727', '772', '813', '850', '863', '904', '941', '954', '229', '404', '478', '706', '770', '912', '808', '319', '515', '563', '641', '712', '208', '217', '309', '312', '618', '630', '708', '773', '815', '847', '219', '260', '317', '574', '765', '812', '316', '620', '785', '913', '270', '502', '606', '859', '225', '318', '337', '504', '985', '413', '508', '617', '781', '978', '301', '410', '207', '231', '248', '269', '313', '517', '586', '616', '734', '810', '906', '989', '218', '320', '507', '612', '651', '763', '952', '314', '417', '573', '636', '660', '816', '228', '601', '662', '406', '252', '336', '704', '828', '910', '919', '701', '308', '402', '603', '201', '609', '732', '856', '908', '973', '505', '575', '702', '775', '212', '315', '516', '518', '585', '607', '631', '716', '718', '845', '914', '216', '330', '419', '440', '513', '614', '740', '937', '405', '580', '918', '503', '541', '215', '412', '570', '610', '717', '724', '814', '401', '803', '843', '864', '605', '423', '615', '731', '865', '901', '931', '210', '214', '254', '281', '325', '361', '409', '432', '512', '713', '806', '817', '830', '903', '915', '936', '940', '956', '972', '979', '435', '801', '276', '434', '540', '703', '757', '804', '802', '206', '253', '360', '425', '509', '262', '414', '608', '715', '920', '304', '307'] },
  uy: { name: 'Uruguay', regions: ['america', 'south-america'], iso2: 'uy', dialCode: '598' },
  uz: { name: 'Uzbekistan', regions: ['asia', 'ex-ussr'], iso2: 'uz', dialCode: '998' },
  vu: { name: 'Vanuatu', regions: ['oceania'], iso2: 'vu', dialCode: '678' },
  va: { name: 'Vatican City', regions: ['europe'], iso2: 'va', dialCode: '39', format: '+.. .. .... ....', priority: 1 },
  ve: { name: 'Venezuela', regions: ['america', 'south-america'], iso2: 've', dialCode: '58' },
  vn: { name: 'Vietnam', regions: ['asia'], iso2: 'vn', dialCode: '84' },
  wf: { name: 'Wallis and Futuna', regions: ['oceania'], iso2: 'wf', dialCode: '681' },
  ye: { name: 'Yemen', regions: ['middle-east'], iso2: 'ye', dialCode: '967' },
  zm: { name: 'Zambia', regions: ['africa'], iso2: 'zm', dialCode: '260' },
  zw: { name: 'Zimbabwe', regions: ['africa'], iso2: 'zw', dialCode: '263' },
};

// Export only the base list of countries (Object.values) and the iso2 dictionary
export const countries: Country[] = Object.values(countriesByIso2);

// countriesByIso2 is already a named export above


